name: tweet_promote_zenn_article

on:
  push:
    branches:
      - main
  # 03:20UTC -> 12:20JST
  schedule:
    - cron: "20 3 * * *"

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - uses: jurassiscripts/setup-velociraptor@v1
      - name: Create env file
        run: |
          cp .env.example .env
          echo TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }} >> .env
          echo TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }} >> .env
          echo TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }} >> .env
          echo TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} >> .env
      - run: VR_HOOKS=false vr promote_zenn_article
