name: welcome

on:
  # 04:10UTC -> 13:10JST
  schedule:
    - cron: "10 4 * * *"

env:
  IFTTT_WEBHOOK_KEY: ${{secrets.IFTTT_WEBHOOK_KEY}}

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run --allow-net --allow-read --allow-read=.env,.env.example,.env.defaults run_promote_zenn_article.ts
