name: tweet_promote_zenn_article

on:
  # push:
  #   branches:
  #     - main
  # 03:20UTC -> 12:20JST
  schedule:
    - cron: "20 3 * * *"

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Create env file
        run: |
          cp .env.example .env
          echo IFTTT_WEBHOOK_KEY=${{ secrets.IFTTT_WEBHOOK_KEY }} >> .env
      - run: deno run --allow-net --allow-read=.env,.env.example,.env.defaults --allow-env promote_zenn_article.ts
