name: sp500_checker

on:
  workflow_dispatch:
  # every sunday morning
  schedule:
    - cron: "0 0 * * 0"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - name: Create env file
        run: |
          cp .env.example .env
          echo LINE_ACCESS_TOKEN=${{ secrets.LINE_ACCESS_TOKEN }} >> .env
          echo TEXTDB_UUID=${{ secrets.TEXTDB_UUID }} >> .env
      - run: deno run --allow-net --allow-env --allow-read sp500_checker.ts
